appearance = {display_sideabar = true, display_description = true, criterias_alphabetic_order = true, tabs_alphabetic_order = false, background_style = "TRANSPARENT", criterias_translation_mode = "ONLY_COMPATIBLE"}
advanced_customization = {header_height = 48, footer_height = 32, criterias_width = 142, above_widget_limit = 14, below_widget_limit = 14}
