[settings]
	#General Settings
	#Maximum distance from where Blocks and Entities can be picked up
	# Default: 2.5
	# Range: 0.0 ~ 1.7976931348623157E308
	maxDistance = 2.5
	#Max width of entities that can be picked up in survival mode
	# Default: 1.5
	# Range: 0.0 ~ 10.0
	maxEntityWidth = 1.5
	#Max height of entities that can be picked up in survival mode
	# Default: 2.5
	# Range: 0.0 ~ 10.0
	maxEntityHeight = 2.0
	#Slowness multiplier for blocks
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	blockSlownessMultiplier = 1.0
	#Slowness multiplier for entities
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	entitySlownessMultiplier = 1.25
	#Maximum stack limit for entities
	# Default: 10
	# Range: > 1
	maxEntityStackLimit = 5
	#More complex Tile Entities slow down the player more
	heavyTiles = true
	#Allow all blocks to be picked up, not just Tile Entites. White/Blacklist will still be respected.
	pickupAllBlocks = false
	#Whether Blocks and Entities slow the creative player down when carried
	slownessInCreative = true
	#Whether hostile mobs should be able to picked up in survival mode
	pickupHostileMobs = false
	#Larger Entities slow down the player more
	heavyEntities = true
	#Allow babies to be carried even when adult mob is blacklisted (or not whitelisted)
	allowBabies = false
	#Use Whitelist instead of Blacklist for Blocks
	useWhitelistBlocks = false
	#Use Whitelist instead of Blacklist for Entities
	useWhitelistEntities = false
	#Use Whitelist instead of Blacklist for Stacking
	useWhitelistStacking = true
	#Whether the player can hit blocks and entities while carrying or not
	hitWhileCarrying = false
	#Whether the player drops the carried object when hit or not
	dropCarriedWhenHit = false
	#Use custom Pickup Scripts. Having this set to false, will not allow you to run scripts, but will increase your performance
	useScripts = true
	#Allows entities to be stacked on top of each other
	stackableEntities = true
	#Whether entities' size matters when stacking or not. This means that larger entities cannot be stacked on smaller ones
	entitySizeMattersStacking = true
	#Usually all the block state information is retained when placing a block that was picked up. But some information is changed to a modified property, like rotation or orientation. In this list, add additional properties that should NOT be saved and instead be updated when placed. Format: modid:block[propertyname]. Note: You don't need to add an entry for every subtype of a same block. For example, we only add an entry for one type of slab, but the change is applied to all slabs.
	placementStateExceptions = ["minecraft:chest[type]", "minecraft:stone_button[face]", "minecraft:vine[north,east,south,west,up]", "minecraft:creeper_head[rotation]", "minecraft:glow_lichen[north,east,south,west,up,down]", "minecraft:oak_sign[rotation]", "minecraft:oak_trapdoor[half]", "sophisticatedbackpacks:backpack[face]"]
	#Whether Players can be picked up. Creative players can't be picked up in Survival Mode
	pickupPlayers = true
	#Whether players in Survival Mode can pick up unbreakable blocks. Creative players always can.
	pickupUnbreakableBlocks = false

[whitelist]
	#Whitelist. Read about the format here: https://github.com/Tschipp/CarryOn/wiki/Black---and-Whitelist-Config
	#Entities that CAN be picked up (useWhitelistEntities must be true)
	allowedEntities = []
	#Blocks that CAN be picked up (useWhitelistBlocks must be true)
	allowedBlocks = []
	#Entities that CAN have other entities stacked on top of them (useWhitelistStacking must be true)
	allowedStacking = ["minecraft:turtle", "alexsmobs:terrapin", "quark:toretoise"]

[blacklist]
	#Blacklist. Read about the format here: https://github.com/Tschipp/CarryOn/wiki/Black---and-Whitelist-Config
	#Blocks that cannot be picked up
	forbiddenTiles = ["#c:immovable", "#c:relocation_not_supported", "minecraft:end_portal", "minecraft:piston_head", "minecraft:end_gateway", "minecraft:tall_grass", "minecraft:large_fern", "minecraft:peony", "minecraft:rose_bush", "minecraft:lilac", "minecraft:sunflower", "minecraft:*_bed", "minecraft:*_door", "minecraft:big_dripleaf_stem", "minecraft:lily_pad", "minecraft:cake", "minecraft:nether_portal", "minecraft:tall_seagrass", "minecraft:jukebox", "create:*", "cobblemon:pc", "cobblemon:pasture", "amendments:carpet_slab", "amendments:carpet_stairs", "supplementaries:rope_knot", "farmersdelight:cutting_board", "handcrafted:*nightstand", "handcrafted:*desk", "handcrafted:*counter", "sophisticatedbackpacks:*", "sophisticatedstorage:*chest", "comforts:*", "supplementaries:urn", "cobblemon:restoration_tank", "cobblemon:fossil_analyzer", "cobblemon:monitor", "cobblemonraiddens:raid_crystal_block", "cobblemonraiddens:raid_home_block"]
	#Entities that cannot be picked up
	forbiddenEntities = ["#c:capturing_not_supported", "#c:teleporting_not_supported", "minecraft:end_crystal", "minecraft:ender_dragon", "minecraft:ghast", "minecraft:fireball", "minecraft:small_fireball", "minecraft:wither_skull", "minecraft:shulker", "minecraft:leash_knot", "minecraft:armor_stand", "minecraft:wither_skull_dangerous", "minecraft:dragon_fireball", "minecraft:item_frame", "minecraft:painting", "minecraft:shulker_bullet", "minecraft:evoker_fangs", "minecraft:glow_item_frame", "minecraft:tnt", "minecraft:trident", "minecraft:arrow", "minecraft:spectral_arrow", "minecraft:marker", "minecraft:block_display", "minecraft:item_display", "minecraft:text_display", "cobblemon:empty_pokeball", "cobblemon:generic_bedrock", "cobblemon:pokemon", "mowziesmobs:boulder_platform", "mowziesmobs:boulder_platform_crumbling", "create:package"]
	#Entities that cannot have other entities stacked on top of them
	forbiddenStacking = ["minecraft:horse", "cobblemon:pokemon"]

[customPickupConditions]
	#Custom Pickup Conditions. Read about the format here: https://github.com/Tschipp/CarryOn/wiki/Custom-Pickup-Condition-Config
	#Custom Pickup Conditions for Blocks
	customPickupConditionsBlocks = []
	#Custom Pickup Conditions for Entities
	customPickupConditionsEntities = []
