# Don't change this! Version used to track needed updates.
version = 0
turnOffPotionParticles = "SELF"
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
disableParticles = false

[byTypeReductions]
"minecraft:entity_effect" = 0.2549019607843137